version: "3.8"
services:
  server:
    container_name: csxp_server
    image: csxpi_server
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/Dockerfile.server
    ports:
      - 8881:80
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
  app:
    container_name: csxp_app
    image: csxpi_app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod.app
    ports:
      - 8880:8880
    depends_on:
      - mysql
      - server
      - analytics
  mysql:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    command: --max_allowed_packet=128000000 #Bytes
    # ports:
    #     - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: csxp_analytics_db
  analytics:
    image: matomo:latest
    container_name: csxp_analytics
    restart: unless-stopped
    volumes:
      - ./analytics:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: csxp_analytics_db
      MATOMO_DATABASE_USERNAME: test
      MATOMO_DATABASE_PASSWORD: test
      MATOMO_DATABASE_DBNAME: analytics
    ports:
      - 8883:80
    links: [mysql]
